# https://dart.dev/guides/language/analysis-options#the-analysis-options-file
#
# Example analyzer config
# https://github.com/flutter/flutter/blob/master/analysis_options.yaml


# https://github.com/dart-lang/pedantic/tree/master/lib
include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore
  exclude:
    - "lib/generated/**"
  enable-experiment:
    - non-nullable
